version: "3.9"

volumes:

    # remembers gz config, downloaded models etc
    gz_config:

services:

  px4_gazebo:
    environment:
      - HOST_UID=1000
      - HOST_GID=1000
      - DISPLAY=$DISPLAY
      - RUN_VNC=false
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
      - PX4_GZ_WORLD=default
      - ROS_DOMAIN_ID=1
      - PX4_MICRODDS_NS=px4_1
    image: pixelinkler/px4-gazebo-docker
    # image: ${REGISTRY}/cognipilot/dream:${TAG}
    deploy:
      resources:
        limits:
          memory: 6G
#    build:
#       dockerfile: Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    hostname: px4_gazebo
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./work:/home/user/work
      - /tmp/.X11-unix:/tmp/.X11-unix
#      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
#      - $HOME/gnupg:/home/user/.gnupg
#      - $HOME/.ssh:/home/user/.ssh
#      - $HOME/.gitconfig:/home/user/.gitconfig
#      - gz_config:/home/user/.gz
